/* Help for binding crso (:dndbspell_lvl_cls): Spells by level, class, etc */

const options = [
    /* components */
    "verbal:	verbal=t",
    "noverbal:	verbal=f",
    "somatic:	somatic=t",
    "nosomatic:	somatic=f",
    "material:	material=t",
    "nomaterial:	material=f",
    "v:	verbal=t",
    "no-v:	verbal=f",
    "s:	somatic=t",
    "no-s:	somatic=f",
    "m:	material=t",
    "no-m:	material=f",
    /* concentration */
    "conc:	concentration=1",
    "noconc:	concentration=2",
    /* ritual */
    "ritual:	ritual=t",
    "noritual:	ritual=f",
    /* casting time */
    "action:	casting-time=1",
    "ba:	casting-time=2",
    "reaction:	casting-time=3",
    "min:	casting-time=4",
    "1min:	casting-time=4",
    "10min:	casting-time=5",
    "hr:	casting-time=6",
    "1hr:	casting-time=6",
    "8hr:	casting-time=7",
    "12hr:	casting-time=8",
    /* school */
    "abjuration:	school=3",
    "conjuration:	school=4",
    "divination:	school=5",
    "enchantment:	school=6",
    "evocation:	school=7",
    "illusion:	school=8",
    "necromancy:	school=9",
    "transmutation:	school=10",
    /* attack type */
    "melee:	attack-type=1",
    "ranged:	attack-type=2",
    /* damage type */
    "acid:	damage-type=48",
    "bludgeoning:	damage-type=49",
    "cold:	damage-type=50",
    "fire:	damage-type=51",
    "force:	damage-type=52",
    "lightning:	damage-type=53",
    "necrotic:	damage-type=54",
    "piercing:	damage-type=55",
    "poison:	damage-type=56",
    "psychic:	damage-type=57",
    "radiant:	damage-type=58",
    "slashing:	damage-type=59",
    "thunder:	damage-type=60",
    /* save */
    "str:	save-required=1",
    "dex:	save-required=2",
    "con:	save-required=3",
    "int:	save-required=4",
    "wis:	save-required=5",
    "cha:	save-required=6",
    "save:	save-required=1&filter-save-required=2&filter-save-required=3&filter-save-required=4"
        + "&filter-save-required=5&filter-save-required=6",
    /* conditions */
    "blinded:	condition=1",
    "charmed:	condition=2",
    "deafened:	condition=3",
    "exhausted:	condition=4",
    "frightened:	condition=5",
    "grappled:	condition=6",
    "incapacitated:	condition=7",
    "invisible:	condition=8",
    "paralyzed:	condition=9",
    "petrified:	condition=10",
    "poisoned:	condition=11",
    "prone:	condition=12",
    "restrained:	condition=13",
    "stunned:	condition=14",
    "unconscious:	condition=15",
    /* sort */
    "sort=cast:	sort=casting-time",
    "sort=-cast:	sort=-casting-time",
    "sort=duration:	sort=spell-duration",
    "sort=-duration:	sort=-spell-duration",
    /* tags */
    "creation:	tags=1",
    "heal:	tags=2",
    "healing:	tags=2",
    "teleport:	tags=4",
    "teleportation:	tags=4",
    "damage:	tags=5",
    "dmg:	tags=5",
    "control:	tags=6",
    "communication:	tags=10",
    "social:	tags=12",
    "debuff:	tags=13",
    "scry:	tags=14",
    "scrying:	tags=14",
    "detect:	tags=15",
    "detection:	tags=15",
    "banish:	tags=16",
    "banishment:	tags=16",
    "move:	tags=17",
    "movement:	tags=17",
    "utility:	tags=19",
    "environment:	tags=20",
    "explore:	tags=21",
    "exploration:	tags=21",
    "combat:	tags=22",
    "shapechange:	tags=23",
    "shapechanging:	tags=23",
    "deception:	tags=24",
    "foreknowledge:	tags=25",
    "warding:	tags=26",
    "compulsion:	tags=66",
    "charm:	tags=108",
    "tag=charmed:	tags=108",
    "special:	tags=187",
    "psi:	tags=301",
    "psionic:	tags=301",
    "dunamancy:	tags=326",
]

cutils.message(options.join("\n"));
